version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
  file_server:
    build:
      context: .
      dockerfile: ./front_end/Dockerfile
    ports:
      - "80:80"
